name: chosen_object
description: "Chosen Object"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.3
  jwt_decoder: ^2.0.1
  http: ^1.2.2
  flutter_map: ^8.3.0
  latlong2: ^0.9.1
  flutter_map_marker_cluster: ^8.2.2
  geolocator: ^14.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
